events {
	# NGINX necesita este bloque obligatoriamente para gestionar las conexiones
	worker_connections 1024;
}

http {
	# Incluir los tipos MIME para que NGINX sepa enviar CSS, JS, etc., correctamente
	include /etc/nginx/mime.types;
	# https://nginx.org/en/docs/http/configuring_https_servers.html
	server {
		listen			443 ssl;
		server_name		jhvalenc.42.fr;
		ssl_certificate		/etc/nginx/ssl/certAutofirmado.crt;
		ssl_certificate_key	/etc/nginx/ssl/certAutofirmado.key;
		ssl_protocols		TLSv1.2 TLSv1.3;

		# El directorio físico donde está montado el volumen wp_data
		root /var/www/html;
		# El archivo que se servirá por defecto
		index index.php index.html;

		# Para las URLs limpias de WordPress
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			# Pasar la ruta absoluta del archivo que PHP debe ejecutar
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
